// =============================================================================
// countryDialCodes — full world country list for the dial-code picker.
// PINNED lists the current curated 30 codes; they appear at the top of the
// dropdown above a divider, with the rest alphabetical by name.
// =============================================================================

export interface DialCountry {
  code: string;  // ISO 3166-1 alpha-2
  name: string;
  dial: string;  // e.g. "+44"
  flag: string;  // emoji flag
}

function flag(iso: string): string {
  return [...iso.toUpperCase()].map((c) => String.fromCodePoint(c.charCodeAt(0) + 127397)).join('');
}

export const COUNTRIES: DialCountry[] = [
  { code: 'AF', name: 'Afghanistan',             dial: '+93',   flag: flag('AF') },
  { code: 'AL', name: 'Albania',                 dial: '+355',  flag: flag('AL') },
  { code: 'DZ', name: 'Algeria',                 dial: '+213',  flag: flag('DZ') },
  { code: 'AD', name: 'Andorra',                 dial: '+376',  flag: flag('AD') },
  { code: 'AO', name: 'Angola',                  dial: '+244',  flag: flag('AO') },
  { code: 'AG', name: 'Antigua & Barbuda',        dial: '+1',    flag: flag('AG') },
  { code: 'AR', name: 'Argentina',               dial: '+54',   flag: flag('AR') },
  { code: 'AM', name: 'Armenia',                 dial: '+374',  flag: flag('AM') },
  { code: 'AU', name: 'Australia',               dial: '+61',   flag: flag('AU') },
  { code: 'AT', name: 'Austria',                 dial: '+43',   flag: flag('AT') },
  { code: 'AZ', name: 'Azerbaijan',              dial: '+994',  flag: flag('AZ') },
  { code: 'BS', name: 'Bahamas',                 dial: '+1',    flag: flag('BS') },
  { code: 'BH', name: 'Bahrain',                 dial: '+973',  flag: flag('BH') },
  { code: 'BD', name: 'Bangladesh',              dial: '+880',  flag: flag('BD') },
  { code: 'BB', name: 'Barbados',                dial: '+1',    flag: flag('BB') },
  { code: 'BY', name: 'Belarus',                 dial: '+375',  flag: flag('BY') },
  { code: 'BE', name: 'Belgium',                 dial: '+32',   flag: flag('BE') },
  { code: 'BZ', name: 'Belize',                  dial: '+501',  flag: flag('BZ') },
  { code: 'BJ', name: 'Benin',                   dial: '+229',  flag: flag('BJ') },
  { code: 'BT', name: 'Bhutan',                  dial: '+975',  flag: flag('BT') },
  { code: 'BO', name: 'Bolivia',                 dial: '+591',  flag: flag('BO') },
  { code: 'BA', name: 'Bosnia & Herzegovina',    dial: '+387',  flag: flag('BA') },
  { code: 'BW', name: 'Botswana',                dial: '+267',  flag: flag('BW') },
  { code: 'BR', name: 'Brazil',                  dial: '+55',   flag: flag('BR') },
  { code: 'BN', name: 'Brunei',                  dial: '+673',  flag: flag('BN') },
  { code: 'BG', name: 'Bulgaria',                dial: '+359',  flag: flag('BG') },
  { code: 'BF', name: 'Burkina Faso',            dial: '+226',  flag: flag('BF') },
  { code: 'BI', name: 'Burundi',                 dial: '+257',  flag: flag('BI') },
  { code: 'CV', name: 'Cape Verde',              dial: '+238',  flag: flag('CV') },
  { code: 'KH', name: 'Cambodia',                dial: '+855',  flag: flag('KH') },
  { code: 'CM', name: 'Cameroon',                dial: '+237',  flag: flag('CM') },
  { code: 'CA', name: 'Canada',                  dial: '+1',    flag: flag('CA') },
  { code: 'CF', name: 'Central African Rep.',    dial: '+236',  flag: flag('CF') },
  { code: 'TD', name: 'Chad',                    dial: '+235',  flag: flag('TD') },
  { code: 'CL', name: 'Chile',                   dial: '+56',   flag: flag('CL') },
  { code: 'CN', name: 'China',                   dial: '+86',   flag: flag('CN') },
  { code: 'CO', name: 'Colombia',                dial: '+57',   flag: flag('CO') },
  { code: 'KM', name: 'Comoros',                 dial: '+269',  flag: flag('KM') },
  { code: 'CG', name: 'Congo (Brazzaville)',     dial: '+242',  flag: flag('CG') },
  { code: 'CD', name: 'Congo (Kinshasa)',         dial: '+243',  flag: flag('CD') },
  { code: 'CR', name: 'Costa Rica',              dial: '+506',  flag: flag('CR') },
  { code: 'CI', name: "Côte d'Ivoire",           dial: '+225',  flag: flag('CI') },
  { code: 'HR', name: 'Croatia',                 dial: '+385',  flag: flag('HR') },
  { code: 'CU', name: 'Cuba',                    dial: '+53',   flag: flag('CU') },
  { code: 'CY', name: 'Cyprus',                  dial: '+357',  flag: flag('CY') },
  { code: 'CZ', name: 'Czechia',                 dial: '+420',  flag: flag('CZ') },
  { code: 'DK', name: 'Denmark',                 dial: '+45',   flag: flag('DK') },
  { code: 'DJ', name: 'Djibouti',                dial: '+253',  flag: flag('DJ') },
  { code: 'DM', name: 'Dominica',                dial: '+1',    flag: flag('DM') },
  { code: 'DO', name: 'Dominican Republic',      dial: '+1',    flag: flag('DO') },
  { code: 'EC', name: 'Ecuador',                 dial: '+593',  flag: flag('EC') },
  { code: 'EG', name: 'Egypt',                   dial: '+20',   flag: flag('EG') },
  { code: 'SV', name: 'El Salvador',             dial: '+503',  flag: flag('SV') },
  { code: 'GQ', name: 'Equatorial Guinea',       dial: '+240',  flag: flag('GQ') },
  { code: 'ER', name: 'Eritrea',                 dial: '+291',  flag: flag('ER') },
  { code: 'EE', name: 'Estonia',                 dial: '+372',  flag: flag('EE') },
  { code: 'SZ', name: 'Eswatini',                dial: '+268',  flag: flag('SZ') },
  { code: 'ET', name: 'Ethiopia',                dial: '+251',  flag: flag('ET') },
  { code: 'FJ', name: 'Fiji',                    dial: '+679',  flag: flag('FJ') },
  { code: 'FI', name: 'Finland',                 dial: '+358',  flag: flag('FI') },
  { code: 'FR', name: 'France',                  dial: '+33',   flag: flag('FR') },
  { code: 'GA', name: 'Gabon',                   dial: '+241',  flag: flag('GA') },
  { code: 'GM', name: 'Gambia',                  dial: '+220',  flag: flag('GM') },
  { code: 'GE', name: 'Georgia',                 dial: '+995',  flag: flag('GE') },
  { code: 'DE', name: 'Germany',                 dial: '+49',   flag: flag('DE') },
  { code: 'GH', name: 'Ghana',                   dial: '+233',  flag: flag('GH') },
  { code: 'GR', name: 'Greece',                  dial: '+30',   flag: flag('GR') },
  { code: 'GD', name: 'Grenada',                 dial: '+1',    flag: flag('GD') },
  { code: 'GT', name: 'Guatemala',               dial: '+502',  flag: flag('GT') },
  { code: 'GN', name: 'Guinea',                  dial: '+224',  flag: flag('GN') },
  { code: 'GW', name: 'Guinea-Bissau',           dial: '+245',  flag: flag('GW') },
  { code: 'GY', name: 'Guyana',                  dial: '+592',  flag: flag('GY') },
  { code: 'HT', name: 'Haiti',                   dial: '+509',  flag: flag('HT') },
  { code: 'HN', name: 'Honduras',                dial: '+504',  flag: flag('HN') },
  { code: 'HU', name: 'Hungary',                 dial: '+36',   flag: flag('HU') },
  { code: 'IS', name: 'Iceland',                 dial: '+354',  flag: flag('IS') },
  { code: 'IN', name: 'India',                   dial: '+91',   flag: flag('IN') },
  { code: 'ID', name: 'Indonesia',               dial: '+62',   flag: flag('ID') },
  { code: 'IR', name: 'Iran',                    dial: '+98',   flag: flag('IR') },
  { code: 'IQ', name: 'Iraq',                    dial: '+964',  flag: flag('IQ') },
  { code: 'IE', name: 'Ireland',                 dial: '+353',  flag: flag('IE') },
  { code: 'IL', name: 'Israel',                  dial: '+972',  flag: flag('IL') },
  { code: 'IT', name: 'Italy',                   dial: '+39',   flag: flag('IT') },
  { code: 'JM', name: 'Jamaica',                 dial: '+1',    flag: flag('JM') },
  { code: 'JP', name: 'Japan',                   dial: '+81',   flag: flag('JP') },
  { code: 'JO', name: 'Jordan',                  dial: '+962',  flag: flag('JO') },
  { code: 'KZ', name: 'Kazakhstan',              dial: '+7',    flag: flag('KZ') },
  { code: 'KE', name: 'Kenya',                   dial: '+254',  flag: flag('KE') },
  { code: 'KI', name: 'Kiribati',                dial: '+686',  flag: flag('KI') },
  { code: 'KW', name: 'Kuwait',                  dial: '+965',  flag: flag('KW') },
  { code: 'KG', name: 'Kyrgyzstan',              dial: '+996',  flag: flag('KG') },
  { code: 'LA', name: 'Laos',                    dial: '+856',  flag: flag('LA') },
  { code: 'LV', name: 'Latvia',                  dial: '+371',  flag: flag('LV') },
  { code: 'LB', name: 'Lebanon',                 dial: '+961',  flag: flag('LB') },
  { code: 'LS', name: 'Lesotho',                 dial: '+266',  flag: flag('LS') },
  { code: 'LR', name: 'Liberia',                 dial: '+231',  flag: flag('LR') },
  { code: 'LY', name: 'Libya',                   dial: '+218',  flag: flag('LY') },
  { code: 'LI', name: 'Liechtenstein',           dial: '+423',  flag: flag('LI') },
  { code: 'LT', name: 'Lithuania',               dial: '+370',  flag: flag('LT') },
  { code: 'LU', name: 'Luxembourg',              dial: '+352',  flag: flag('LU') },
  { code: 'MG', name: 'Madagascar',              dial: '+261',  flag: flag('MG') },
  { code: 'MW', name: 'Malawi',                  dial: '+265',  flag: flag('MW') },
  { code: 'MY', name: 'Malaysia',                dial: '+60',   flag: flag('MY') },
  { code: 'MV', name: 'Maldives',                dial: '+960',  flag: flag('MV') },
  { code: 'ML', name: 'Mali',                    dial: '+223',  flag: flag('ML') },
  { code: 'MT', name: 'Malta',                   dial: '+356',  flag: flag('MT') },
  { code: 'MH', name: 'Marshall Islands',        dial: '+692',  flag: flag('MH') },
  { code: 'MR', name: 'Mauritania',              dial: '+222',  flag: flag('MR') },
  { code: 'MU', name: 'Mauritius',               dial: '+230',  flag: flag('MU') },
  { code: 'MX', name: 'Mexico',                  dial: '+52',   flag: flag('MX') },
  { code: 'FM', name: 'Micronesia',              dial: '+691',  flag: flag('FM') },
  { code: 'MD', name: 'Moldova',                 dial: '+373',  flag: flag('MD') },
  { code: 'MC', name: 'Monaco',                  dial: '+377',  flag: flag('MC') },
  { code: 'MN', name: 'Mongolia',                dial: '+976',  flag: flag('MN') },
  { code: 'ME', name: 'Montenegro',              dial: '+382',  flag: flag('ME') },
  { code: 'MA', name: 'Morocco',                 dial: '+212',  flag: flag('MA') },
  { code: 'MZ', name: 'Mozambique',              dial: '+258',  flag: flag('MZ') },
  { code: 'MM', name: 'Myanmar',                 dial: '+95',   flag: flag('MM') },
  { code: 'NA', name: 'Namibia',                 dial: '+264',  flag: flag('NA') },
  { code: 'NR', name: 'Nauru',                   dial: '+674',  flag: flag('NR') },
  { code: 'NP', name: 'Nepal',                   dial: '+977',  flag: flag('NP') },
  { code: 'NL', name: 'Netherlands',             dial: '+31',   flag: flag('NL') },
  { code: 'NZ', name: 'New Zealand',             dial: '+64',   flag: flag('NZ') },
  { code: 'NI', name: 'Nicaragua',               dial: '+505',  flag: flag('NI') },
  { code: 'NE', name: 'Niger',                   dial: '+227',  flag: flag('NE') },
  { code: 'NG', name: 'Nigeria',                 dial: '+234',  flag: flag('NG') },
  { code: 'MK', name: 'North Macedonia',         dial: '+389',  flag: flag('MK') },
  { code: 'NO', name: 'Norway',                  dial: '+47',   flag: flag('NO') },
  { code: 'OM', name: 'Oman',                    dial: '+968',  flag: flag('OM') },
  { code: 'PK', name: 'Pakistan',                dial: '+92',   flag: flag('PK') },
  { code: 'PW', name: 'Palau',                   dial: '+680',  flag: flag('PW') },
  { code: 'PA', name: 'Panama',                  dial: '+507',  flag: flag('PA') },
  { code: 'PG', name: 'Papua New Guinea',        dial: '+675',  flag: flag('PG') },
  { code: 'PY', name: 'Paraguay',                dial: '+595',  flag: flag('PY') },
  { code: 'PE', name: 'Peru',                    dial: '+51',   flag: flag('PE') },
  { code: 'PH', name: 'Philippines',             dial: '+63',   flag: flag('PH') },
  { code: 'PL', name: 'Poland',                  dial: '+48',   flag: flag('PL') },
  { code: 'PT', name: 'Portugal',                dial: '+351',  flag: flag('PT') },
  { code: 'QA', name: 'Qatar',                   dial: '+974',  flag: flag('QA') },
  { code: 'RO', name: 'Romania',                 dial: '+40',   flag: flag('RO') },
  { code: 'RU', name: 'Russia',                  dial: '+7',    flag: flag('RU') },
  { code: 'RW', name: 'Rwanda',                  dial: '+250',  flag: flag('RW') },
  { code: 'KN', name: 'Saint Kitts & Nevis',     dial: '+1',    flag: flag('KN') },
  { code: 'LC', name: 'Saint Lucia',             dial: '+1',    flag: flag('LC') },
  { code: 'VC', name: 'Saint Vincent',           dial: '+1',    flag: flag('VC') },
  { code: 'WS', name: 'Samoa',                   dial: '+685',  flag: flag('WS') },
  { code: 'SM', name: 'San Marino',              dial: '+378',  flag: flag('SM') },
  { code: 'ST', name: 'São Tomé & Príncipe',     dial: '+239',  flag: flag('ST') },
  { code: 'SA', name: 'Saudi Arabia',            dial: '+966',  flag: flag('SA') },
  { code: 'SN', name: 'Senegal',                 dial: '+221',  flag: flag('SN') },
  { code: 'RS', name: 'Serbia',                  dial: '+381',  flag: flag('RS') },
  { code: 'SC', name: 'Seychelles',              dial: '+248',  flag: flag('SC') },
  { code: 'SL', name: 'Sierra Leone',            dial: '+232',  flag: flag('SL') },
  { code: 'SG', name: 'Singapore',               dial: '+65',   flag: flag('SG') },
  { code: 'SK', name: 'Slovakia',                dial: '+421',  flag: flag('SK') },
  { code: 'SI', name: 'Slovenia',                dial: '+386',  flag: flag('SI') },
  { code: 'SB', name: 'Solomon Islands',         dial: '+677',  flag: flag('SB') },
  { code: 'SO', name: 'Somalia',                 dial: '+252',  flag: flag('SO') },
  { code: 'ZA', name: 'South Africa',            dial: '+27',   flag: flag('ZA') },
  { code: 'SS', name: 'South Sudan',             dial: '+211',  flag: flag('SS') },
  { code: 'ES', name: 'Spain',                   dial: '+34',   flag: flag('ES') },
  { code: 'LK', name: 'Sri Lanka',               dial: '+94',   flag: flag('LK') },
  { code: 'SD', name: 'Sudan',                   dial: '+249',  flag: flag('SD') },
  { code: 'SR', name: 'Suriname',                dial: '+597',  flag: flag('SR') },
  { code: 'SE', name: 'Sweden',                  dial: '+46',   flag: flag('SE') },
  { code: 'CH', name: 'Switzerland',             dial: '+41',   flag: flag('CH') },
  { code: 'SY', name: 'Syria',                   dial: '+963',  flag: flag('SY') },
  { code: 'TW', name: 'Taiwan',                  dial: '+886',  flag: flag('TW') },
  { code: 'TJ', name: 'Tajikistan',              dial: '+992',  flag: flag('TJ') },
  { code: 'TZ', name: 'Tanzania',                dial: '+255',  flag: flag('TZ') },
  { code: 'TH', name: 'Thailand',                dial: '+66',   flag: flag('TH') },
  { code: 'TL', name: 'Timor-Leste',             dial: '+670',  flag: flag('TL') },
  { code: 'TG', name: 'Togo',                    dial: '+228',  flag: flag('TG') },
  { code: 'TO', name: 'Tonga',                   dial: '+676',  flag: flag('TO') },
  { code: 'TT', name: 'Trinidad & Tobago',       dial: '+1',    flag: flag('TT') },
  { code: 'TN', name: 'Tunisia',                 dial: '+216',  flag: flag('TN') },
  { code: 'TR', name: 'Turkey',                  dial: '+90',   flag: flag('TR') },
  { code: 'TM', name: 'Turkmenistan',            dial: '+993',  flag: flag('TM') },
  { code: 'TV', name: 'Tuvalu',                  dial: '+688',  flag: flag('TV') },
  { code: 'UG', name: 'Uganda',                  dial: '+256',  flag: flag('UG') },
  { code: 'UA', name: 'Ukraine',                 dial: '+380',  flag: flag('UA') },
  { code: 'AE', name: 'United Arab Emirates',    dial: '+971',  flag: flag('AE') },
  { code: 'GB', name: 'United Kingdom',          dial: '+44',   flag: flag('GB') },
  { code: 'US', name: 'United States',           dial: '+1',    flag: flag('US') },
  { code: 'UY', name: 'Uruguay',                 dial: '+598',  flag: flag('UY') },
  { code: 'UZ', name: 'Uzbekistan',              dial: '+998',  flag: flag('UZ') },
  { code: 'VU', name: 'Vanuatu',                 dial: '+678',  flag: flag('VU') },
  { code: 'VA', name: 'Vatican City',            dial: '+39',   flag: flag('VA') },
  { code: 'VE', name: 'Venezuela',               dial: '+58',   flag: flag('VE') },
  { code: 'VN', name: 'Vietnam',                 dial: '+84',   flag: flag('VN') },
  { code: 'YE', name: 'Yemen',                   dial: '+967',  flag: flag('YE') },
  { code: 'ZM', name: 'Zambia',                  dial: '+260',  flag: flag('ZM') },
  { code: 'ZW', name: 'Zimbabwe',                dial: '+263',  flag: flag('ZW') },
];

// Codes shown pinned at top of the picker (dance-audience priority).
export const PINNED = [
  'GB','ES','FR','IT','DE','IE','PT','NL','BE','CH',
  'AT','SE','NO','DK','FI','PL','CZ',
  'US','CA','MX','DO','CO','AR','BR','CL','PE','VE',
  'AU','NZ','JP',
];
