# -*- coding: utf-8 -*-
import glob
import re

files_to_fix = [
    'src/pages/Experience.tsx',
    'src/components/PeopleFocusSection.tsx'
]

# Regex to find naked escape sequences like \u{1234} in JSX and wrap them in {'...'}
# Pattern: looks for \u{...} that isn't inside quotes or braces
# This is tricky with regex alone, but we can look for specific expected sequences 
# generated by previous scripts.
# Previous script generated literals like: >\u{1F30E}<

replacements = {
    r">\\u\{1F30E\}<": ">{'\\u1F30E'}<", 
    r">\\u\{1F3A5\}<": ">{'\\u1F3A5'}<", 
    r">\\u\{1F483\}<": ">{'\\u1F483'}<",
    r">\\u\{1F393\}<": ">{'\\u1F393'}<",
    r">\\u\{1F3A7\}<": ">{'\\u1F3A7'}<",
    r">\\u\{1F496\}<": ">{'\\u1F496'}<"
}

for filepath in files_to_fix:
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
        
        new_content = content
        for pattern, replacement in replacements.items():
            new_content = re.sub(pattern, replacement, new_content)
            
        if new_content != content:
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(new_content)
            print(f"Fixed JSX braces in {filepath}")
        else:
            print(f"No JSX braces needed index in {filepath}")

    except Exception as e:
        print(f"Error {filepath}: {e}")
