export const DASHBOARD_LABELS = {
  addFaq: 'Add FAQ',
  addClass: 'Add Class',
  addEvent: 'Add Event',
  addGig: 'Add Gig',
  addProduct: 'Add Product',
  addPromo: 'Add Promo',
  addImages: 'Add Images',
  addReel: 'Add Reel',
  addItem: 'Add Item',
  manage: 'Manage',
  manageProfile: 'Manage Profile',
  managePartners: 'Manage Partners',
  manageEvents: 'Manage Events',
  manageCalendar: 'Manage Calendar',
  manageClasses: 'Manage Classes',
  manageProducts: 'Manage Products',
  manageInventory: 'Manage Inventory',
  manageMixes: 'Manage Mixes',
  manageReels: 'Manage Reels',
  update: 'Update',
  updateProfile: 'Update Profile',
  updateFaq: 'Update FAQ',
  updatePromo: 'Update Promo',
  updateLinks: 'Update Links',
  updateContact: 'Update Contact',
  updateLogo: 'Update Logo',
  updateShipping: 'Update Shipping',
  updateVisibility: 'Update Visibility',
  updateStatus: 'Update Status',
  updatePreferences: 'Update Preferences',
  updateAvailability: 'Update Availability',
} as const;
