// One-shot generator: bundles the brand TTFs into api/og/_fonts.ts as base64 so
// the OG-card serverless function never depends on Vercel file-tracing of loose
// assets. Re-run if the fonts change, then delete the raw .ttf files.
import { readFileSync, writeFileSync } from 'node:fs';

const fonts = [
  ['FONT_INTER_REGULAR', 'api/og/_fonts/Inter-Regular.ttf'],
  ['FONT_INTER_SEMIBOLD', 'api/og/_fonts/Inter-SemiBold.ttf'],
  ['FONT_FRAUNCES_SEMIBOLD', 'api/og/_fonts/Fraunces-SemiBold.ttf'],
];

let out = `// AUTO-GENERATED by scripts/_gen-fonts.mjs — do not edit by hand.\n`;
out += `// Brand fonts for the OG-card endpoint, base64-embedded so they bundle\n`;
out += `// deterministically into the serverless function.\n\n`;
for (const [name, path] of fonts) {
  const b64 = readFileSync(path).toString('base64');
  out += `export const ${name} = Buffer.from(\n  '${b64}',\n  'base64',\n);\n\n`;
}
writeFileSync('api/og/_fonts.ts', out);
console.log('wrote api/og/_fonts.ts');
