#!/usr/bin/env bash
# check-source-integrity.sh
# Defends against Cowork-mount file corruption. Two checks:
#   1. Null bytes in source files (the classic symptom).
#   2. Strict JSON files parse correctly (catches mid-content truncation).
#
# Files known to use JSON-with-comments (jsonc) are skipped from the parse check:
#   - tsconfig*.json (TypeScript convention)
#   - .vscode/*.json (editor settings)
#   - package-lock.json (regenerated by npm; shouldn't be hand-edited)
#
# Exit 0 if clean, 1 if any file is corrupted.
#
# Usage:
#   bash scripts/check-source-integrity.sh                  # scan all tracked source files
#   bash scripts/check-source-integrity.sh --staged         # scan only staged files (used by pre-commit hook)

set -euo pipefail

mode="${1:-all}"

if [ "$mode" = "--staged" ]; then
    files=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(ts|tsx|js|jsx|cjs|mjs|json|md|sql|yml|yaml|html|css|sh)$' || true)
else
    files=$(git ls-files '*.ts' '*.tsx' '*.js' '*.jsx' '*.cjs' '*.mjs' '*.json' '*.md' '*.sql' '*.yml' '*.yaml' '*.html' '*.css' '*.sh')
fi

if [ -z "$files" ]; then
    echo "check-source-integrity: no source files to scan"
    exit 0
fi

# Files allowed to fail strict-JSON parse (jsonc-by-convention or auto-generated)
is_strict_json_skip() {
    case "$1" in
        *tsconfig*.json|.vscode/*.json|package-lock.json) return 0 ;;
        *) return 1 ;;
    esac
}

null_corrupted=()
json_corrupted=()
scanned=0

while IFS= read -r f; do
    [ -z "$f" ] && continue
    [ -f "$f" ] || continue
    scanned=$((scanned + 1))

    # Check 1: null bytes (via tr — portable, immune to grep quoting quirks)
    nulls=$(LC_ALL=C tr -d -c '\0' < "$f" | wc -c | tr -d ' ')
    if [ "$nulls" -gt 0 ]; then
        null_corrupted+=("$f ($nulls null bytes)")
        continue
    fi

    # Check 2: strict JSON parse (only for .json files NOT in the skip list)
    case "$f" in
        *.json)
            if ! is_strict_json_skip "$f"; then
                if command -v python3 >/dev/null 2>&1; then
                    if ! python3 -c "import json,sys; json.load(open(sys.argv[1]))" "$f" 2>/dev/null; then
                        json_corrupted+=("$f")
                    fi
                elif command -v node >/dev/null 2>&1; then
                    if ! node -e "JSON.parse(require('fs').readFileSync(process.argv[1],'utf8'))" "$f" 2>/dev/null; then
                        json_corrupted+=("$f")
                    fi
                fi
            fi
            ;;
    esac
done <<< "$files"

null_count=${#null_corrupted[@]}
json_count=${#json_corrupted[@]}
total=$((null_count + json_count))

if [ "$total" -gt 0 ]; then
    if [ "$null_count" -gt 0 ]; then
        echo "check-source-integrity: $null_count file(s) contain null bytes:"
        for entry in "${null_corrupted[@]}"; do
            echo "   - $entry"
        done
    fi
    if [ "$json_count" -gt 0 ]; then
        echo "check-source-integrity: $json_count JSON file(s) fail to parse (likely truncated):"
        for entry in "${json_corrupted[@]}"; do
            echo "   - $entry"
        done
    fi
    echo ""
    echo "These files are corrupted (likely from a Cowork sandbox Write/Edit on the Windows mount)."
    echo "Repair by rewriting via scripts/safe-write.py:"
    echo "    cat /tmp/clean-content | python3 scripts/safe-write.py path/to/file"
    exit 1
fi

echo "check-source-integrity: $scanned files scanned, 0 corrupted"
exit 0
