// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // SSR-safe: in the browser this is the exact same object as the old bare
    // `localStorage`; when window is absent (node/SSR) it is omitted and
    // auth-js falls back to its in-memory adapter (GoTrueClient: `if
    // (settings.storage)`). Keeps this file safe to import server-side. NOTE:
    // this file is auto-generated -- tests/ssr/eventPageSsr.test.tsx guards
    // against a regeneration reintroducing the bare `localStorage`.
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});